config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles
  resources :categories
  root 'articles#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  # required data
  validates :content, :presence => true
  validates :title, :presence => true
  validates :summary, :presence => true
  validates :category_id, :presence => true
  
  # Associations
  belongs_to :user
  belongs_to :category
  
  # Image upload - paperclip
  has_attached_file :article_img, styles: { article_show: "1000x1000>", article_index: "500x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :article_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Associations
  has_many :articles
  
  # Image upload - paperclip
  has_attached_file :category_img, styles: { category_show: "1000x1000>", category_index: "500x500>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :category_img, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # Associations       
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]


  def index
    if params[:category].blank?
      # @articles vairable with pagination and without category filter
      @articles = Article.all.paginate(page: params[:page], per_page: 5).order("created_at DESC")
    else
      # Category varviables
      @category_id = params[:category]
      @category_name = Category.find(@category_id).name
      # @articles variable with category filter and pagination
      @articles = Article.where(:category_id => @category_id).paginate(page: params[:page], per_page: 5).order("created_at DESC")
    end
  end


  def show
  end

  
  def new
    # Assign global variables
    @article = current_user.articles.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  
  def create
    # Global variables
    @article = current_user.articles.build(article_params)
    @article.category_id = params[:category_id]

    # Article save functionality
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.', change: true }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    # global variable
    @article.category_id = params[:category_id]
    # Article update functionality
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # Private methods
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :category_id, :article_img, :summary)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  def index
    @categories = Category.all.order("name ASC")
  end


  def show
  end


  def new
    @category = Category.new
  end


  def edit
  end


  def create
    @category = Category.new(category_params)
    
    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end
  
  
  # Private methods
  private
    def set_category
      @category = Category.find(params[:id])
    end
    
    def category_params
      params.require(:category).permit(:name, :category_img)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="article-head-section">
  <!-- Article category -->
  <h4 class="article-date">
    <%= article.created_at.strftime("%B") %> 
    <span class="article-date-day"><%= article.created_at.strftime("%e") %></span><span class="article-date-ordinal-indicator"></span>, <%= article.created_at.strftime("%Y")%>
  </h4>
  
  <!-- Article title -->
  <a href="/articles/<%= article.id %>" target="-blank">
    <h1 class="article-show-headline"><%= article.title %>&nbsp;<i class="fa fa-angle-right"></i></h1>
  </a>
  <h4>
    <!-- Article author -->
    <span class="article-author"><%= article.user.first_name%> <%= article.user.last_name%></span> &#9679;
    <!-- Responsive date element. Uses js file to adapt the ordinal indicator to the article date i.e. 1st, 2nd, 3rd etc -->
    <% if article.category_id %>
      <span class="article-category"><%= article.category.name %></span>
    <% end %>
    
  </h4>
  <p class="article-index-summary">
    <%= article.summary %>
  </p>
  
  <!-- Edit/Delete buttons -->
  <% if user_signed_in? %>
    <% if current_user.id == article.user_id %>
      <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_article_path(article), class: "index-user-button"%>
      &nbsp
      <%= link_to '<i class="fa fa-window-close"></i>'.html_safe, article, method: :delete, data: { confirm: 'Are you sure?'}, class: "index-user-button"%>
    <% end %>
  <% end %>
</div>

<!-- Article image - appears large and centered -->
<div class="text-center">
  <% if article.article_img_content_type %>
    <%= image_tag article.article_img.url(:article_show), class: "img-show" %>
  <% else %>
    <%= image_tag article.category.category_img.url(:category_show), class: "img-show" %>
  <% end %>
</div>
<br>

<!-- Main article content -->
<div class="article-body">
  <p><%= article.content.html_safe %></p>
</div>


<div class="article-index-bottom-padding"></div>

<div class="text-center article-separator">
  <i class="fa fa-bolt"></i>
</div>

app/views/articles/_form.html.erb
<!-- Form partial for article -->


<!-- Initialises tinyMCE -->
<%= tinymce %>
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <!-- various form fields for article info -->
  <div class="field">
    <%= f.file_field :article_img, label: "Add Image" %>
  </div>
  
  <div>
    <%= label_tag "Select Category:" %><br />
    <%= select_tag(:category_id, options_for_select(@categories, Category.find(1))) %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary, :rows => 3, :cols => 60, class: "mceNoEditor" %>
  </div>
  
  <!-- tinyMCE element - rich text editor -->
  <div>
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => "tinymce", :rows => 20, :cols => 120 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 1;
<% end %>

<!-- tinyMCE initialisation for rich text editing -->
<%= tinymce_assets %>
<%= tinymce %>

<h1>Edit Article</h1>

<!-- Form fields for article info -->
<!-- This page doesn't render the form partial due to issues with the category dropdown -->
<%= simple_form_for @article, :html => { :multipart => true } do |f| %>

  <div class="field">
    <%= f.file_field :article_img, label: "Add Image" %>
  </div>

  <%= f.select :category_id, @categories, label: "Select Category" %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <!-- tinyMCE editor -->
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary, :rows => 3, :cols => 60, class: "mceNoEditor"%>
  </div>
  
  <div>
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => "tinymce", :rows => 20, :cols => 120 %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>


<!-- Links to show and 'back' -->
<%= link_to '<p class="article-back-btn"> Show Article </p>'.html_safe, @article %> <br>
<%= link_to '<p class="article-back-btn"> <i class= "fa fa-arrow-left"></i> Back </p>'.html_safe, :back %>

app/views/articles/index.html.erb
<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 1
<% end %>

<!-- Assigns value to @title variable -->
<% if params[:category].blank? %>
  <% @title = "Articles" %> <!-- Defaults to 'Articles' if no filter applied -->
<% else %>
  <% @title = @category_name %> <!-- Assigned to category name, if the filter is applied -->
<% end %>


<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <!-- If the user is sign in they will see a button to create a new article -->
    <% if user_signed_in? %>
      <%= link_to 'New Article', new_article_path, class:"btn btn-primary btn-block" %>
    <% end %>
    <br />
    
    <!-- Rails in-built functionaility allows each of the articles to be rendered with a simple command: -->
    <%= render @articles %>
    
  </div>
</div>

<!-- Pagination block sits at the bottom, above the footer -->
<div class="text-center">
  <%= will_paginate @articles, renderer: BootstrapPagination::Rails %>
</div>

app/views/articles/new.html.erb
<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 1;
<% end %>

<!-- New article page -->
<%= tinymce_assets %> <!-- requirement for rich text editor --> 
<h1>New Article</h1>

<!-- Renders the form -->
<%= render 'form' %>

<!-- Back button -->
<%= link_to '<p class="article-back-btn"> <i class= "fa fa-arrow-left"></i> Back </p>'.html_safe, :back %>

app/views/articles/show.html.erb
<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 1;
<% end %>

<!-- Assigns value to @title variable -->
<% @title = @article.title %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="article-head-section">
      <!-- Article category -->
      <h4 class="article-date">
        <%= @article.created_at.strftime("%B") %>
        <span class="article-date-day"><%= @article.created_at.strftime("%e") %></span><span class="article-date-ordinal-indicator"></span>, <%= @article.created_at.strftime("%Y")%>
      </h4>
      
      <!-- Article title -->
      
      <h1 class="article-show-headline"><%= @article.title %></h1>
      <h4>
        <!-- Article author -->
        <span class="article-author"><%= @article.user.first_name%> <%= @article.user.last_name%></span> &#9679;
        <!-- Responsive date element. Uses js file to adapt the ordinal indicator to the article date i.e. 1st, 2nd, 3rd etc -->
        <% if @article.category_id %>
          <span class="article-category"><%= @article.category.name %></span>
        <% end %>
        
      </h4>
      <p class="article-index-summary">
        <%= @article.summary %>
      </p>
      
      <!-- Edit/Delete buttons -->
      <% if user_signed_in? %>
        <% if current_user.id == @article.user_id %>
          <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_article_path(@article), class: "index-user-button"%>
          &nbsp;
          <%= link_to '<i class="fa fa-window-close"></i>'.html_safe, @article, method: :delete, data: { confirm: 'Are you sure?'}, class: "index-user-button"%>
        <% end %>
      <% end %>
    </div>
    
    <!-- Article image - appears large and centered -->
    <div class="text-center">
      <% if @article.article_img_content_type %>
        <%= image_tag @article.article_img.url(:article_show), class: "img-show" %>
      <% else %>
        <%= image_tag @article.category.category_img.url(:category_show), class: "img-show" %>
      <% end %>
    </div>
    <br>
    
    <!-- Main article content -->
    <div class="article-body">
      <p><%= @article.content.html_safe %></p>
    </div>
    
    <!-- Article footer -->
    <div class="article-index-bottom-padding"></div>
    
    <!-- Back Button -->
    <%= link_to '<p class="article-back-btn"> <i class= "fa fa-arrow-left"></i> Back </p>'.html_safe, :back %>
    
  </div>
</div>

app/views/categories/_form.html.erb
<!-- Category form -->
<!-- Basic form fields -->
<!-- Not public front end so doesn't have to be production standard -->
<%= simple_form_for @category do |f|%>
  <%= f.input :name, label: "Category Name" %>
  <%= f.file_field :category_img %>
  <%= f.button :submit %>
<% end %>

app/views/categories/edit.html.erb
<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 5;
<% end %>

<h1>Edit Category</h1>

<%= render "form" %>

app/views/categories/index.html.erb
<!-- Category index page -->
<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 5;
<% end %>

<h1>Categories</h1>

<!-- Links to each category as well as new category form -->
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category %><br></li>
  <% end %>
</ul>
<h6><%= link_to "New Category", new_category_path %></h6>

app/views/categories/new.html.erb
<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 5;
<% end %>

<h1>New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<!-- Cateogry show page -->
<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 5;
<% end %>

<!-- Shows category name and default image -->
<h1>Category: <%= @category.name %></h1>
<% if @category.category_img_content_type %>
  <h1>Image: </h1>
  <%= image_tag @category.category_img.url(:category_index) %>
<% end %>

<br><br>
<!-- Options to edit/delete category -->
<%= link_to 'Edit', edit_category_path(@category), class: "btn btn-primary" %>
<%= link_to 'Delete', category_path, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- looks for variable @title, defaults to "MG" -->
  <title><%= @title || "Matthew Gillespie" %></title> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Loads Favicon from file -->
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <!-- HEADER SECTION -->
  <div class="container text-center">
    <a href="/" class="header-link"> <!-- Links to root -->
      <h1 class="header-name">
        Matthew Gillespie
      </h1>
    </a>
  </div>
  
  <!-- NAVBAR SECTION-->  
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <!-- Article dropdown menu -->
            <a href="#" class="dropdown-toggle navbar-articles" data-toggle="dropdown" role="button" aria-expanded="false">Portfolio<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% if user_signed_in? %>
                <li><%= link_to "New", new_article_path %></li><!-- Link to new article form -->
              <% end %>
              <li><%= link_to "All", articles_path %></li><!-- link to index page without filter -->
              <% Category.all.each do |category| %>
                <li class="<%= 'active' if @category_name == category.name %>">
                  <%= link_to category.name, articles_path(category: category.id), class: "link" %><!-- link to index page with filter for each category -->
                </li>
              <% end %>
            </ul>
          </li>
          <!-- Link to About and Contact pages-->
          <li><%= link_to "About", about_path, class: "navbar-about" %></li>
          <li><%= link_to "Contact", contact_path, class: "navbar-contact" %></li>
          
          <% if user_signed_in? %>
            <!-- Links for user -->
            <li><%=link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li><%=link_to "Edit Profile", edit_user_registration_path, class: "navbar-edit-profile" %></li>
            <li><%=link_to "Categories", categories_path, class: "navbar-categories" %></li>
          <% end %>
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
          
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
  
  
  <!-- MAIN PAGE CONTENT -->
  <div class="container main-section">
    <%= yield %>
  </div>
  
  
  <!-- FOOTER SECTION -->
  <div class="footer">
    <div class="container text-center">
      <div class="footer-container">
        
        
        <div class="footer-copyright">
          <p><i class="fa fa-copyright"></i> 2017 Matthew Gillespie</p>
          <p>All rights reserved</p>
        </div>
        
        
        <!-- links for social media -->
        <!--
        <a href="https://twitter.com/alexmgillespie" class="twitter-btn" target="_blank">
          <i class="fa fa-twitter"></i>
        </a>
        &nbsp;
        <a href="#" class="linkedin-btn" taget="_blank">
          <i class="fa fa-linkedin"></i>
        </a>
        &nbsp;
        <a href="https://www.instagram.com/alexgillespie/" class="insta-btn" target="_blank">
          <i class="fa fa-instagram"></i>
        </a>
        -->
      </div>
    </div>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<!-- Assigns value to @title variable -->
<% @title = "About Me" %>

<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 2;
<% end %>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="text-center">
      <!-- About heading
      <h1 class="about-heading">About Me</h1>
      -->
    </div>
    <div>
      <!-- Simple profile image with circular border -->
      <%= image_tag "profile1.jpg", class: "text-center profile-image" %>
      <!-- A few articles listing info, achievements etc -->
      <p class="about-content">
      Matthew is a 20 year old writer and student from Glasgow. His work is mainly focused around fashion and wider culture.
      <br><br>
      </p>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<!-- Assigns value to @title variable -->
<% @title = "Contact" %>

<!-- assigns variable 'nav' to enable navbar highlighting -->
<%= javascript_tag do %>
  nav = 3;
<% end %>

<div class="text-center">
  <!-- Contact heading
  <h1 class="contact-heading">Contact</h1>
  -->
  
  <h3>
    <!-- Simple message
    If you have any questions, please feel free to get in touch:<br>
    -->
    <div class="row">
      <div class="col-md-6 col-md-offset-3 contact-list">
        <!-- Links to email, social media etc -->
        <a href="mailto:0matthewgillepsie0@gmail.com" target="_blank">
          <i class="fa fa-envelope"></i> 0matthewgillespie0@gmail.com
        </a><br>
        <span>
          <i class="fa fa-phone"></i> +447935889746
        </span><br>
        <!--
        <a href="#" target="_blank">
          <i class="fa fa-twitter"></i> @TwitterHandle
        </a><br>
        -->
        <!--
        <a href="#" target="_blank">
          <i class="fa fa-instagram"></i> @IGhandle
        </a><br>
        -->
        <!--
        <a href="#" target="_blank">
          <i class="fa fa-linkedin"></i> MatthewGillespie
        </a><br>
        -->
      </div>
    </div>
  </h3>
</div>